"""empty message

Revision ID: 746fb8736405
Revises: dea737262fd3
Create Date: 2023-08-03 00:37:26.469433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '746fb8736405'
down_revision = 'dea737262fd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.alter_column('artwork',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)

    with op.batch_alter_table('tracklist', schema=None) as batch_op:
        batch_op.alter_column('cover_image',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)

    with op.batch_alter_table('tracklists', schema=None) as batch_op:
        batch_op.drop_constraint('tracklists_tracklist_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('tracklists_song_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'songs', ['song_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'tracklist', ['tracklist_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('profile_image',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('profile_image',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)

    with op.batch_alter_table('tracklists', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tracklists_song_id_fkey', 'songs', ['song_id'], ['id'])
        batch_op.create_foreign_key('tracklists_tracklist_id_fkey', 'tracklist', ['tracklist_id'], ['id'])

    with op.batch_alter_table('tracklist', schema=None) as batch_op:
        batch_op.alter_column('cover_image',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)

    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.alter_column('artwork',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###
