"""empty message

Revision ID: cd17189d7457
Revises: 5615d9bc4799
Create Date: 2023-07-28 11:59:38.687439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd17189d7457'
down_revision = '5615d9bc4799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('cover_image', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Tracklists')
    with op.batch_alter_table('tracklists', schema=None) as batch_op:
        batch_op.drop_constraint('tracklists_tracklist_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tracklist', ['tracklist_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracklists', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tracklists_tracklist_id_fkey', 'tracklists', ['tracklist_id'], ['id'])

    op.create_table('Tracklists',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Tracklists_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('cover_image', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('public', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='Tracklists_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Tracklists_pkey')
    )
    op.drop_table('tracklist')
    # ### end Alembic commands ###
